# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'testingMvvmRx' do
  use_frameworks!

    pod 'RxSwift', '~> 4.0'
    pod 'RxCocoa', '~> 4.0'
    pod 'SnapKit', '~> 4.0.0'

    target 'testingMvvmRxTests' do
        inherit! :search_paths
        # Pods for testing

        pod 'RxBlocking', '~> 4.0'
        pod 'RxTest',     '~> 4.0'
    end

end
